learn_to_code/client_app/urls.py
from django.urls import path
from client_app import views

app_name = 'client_app'
urlpatterns = [
    path('client_registration/', views.client_registration, name='client_registration'),
    path('client_login/', views.client_login, name='client_login'),
    path('client_logout/', views.client_logout, name='client_logout'),
    path('code/', views.code, name="client_code"),
    path('code/<int:lesson_number>/', views.code, name='lesson_detail'),
    path('lessons/', views.lessons, name='client_lessons'),
    path('client_reset_progress/', views.reset, name="client_reset_progress"),
    path('complete_lesson/', views.complete_lesson, name='complete_lesson')
]

learn_to_code/learn_to_code/urls.py
from django.contrib import admin
from django.urls import path, include
from client_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('client_app/', include('client_app.urls')),
]

learn_to_code/client_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Lesson(models.Model):
    number = models.IntegerField(primary_key=True, default=1)
    name = models.CharField(max_length=30, default="Not set")

    def __str__(self):
        return self.name


class Badge(models.Model):
    name = models.CharField(max_length=30, default="Not set")
    icon = models.ImageField(upload_to="badges")
    lesson_requirement = models.IntegerField(default=1)


class ClientProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    current_lesson = models.CharField(max_length=30, blank=True)
    completed_lessons = models.ManyToManyField(Lesson)
    badges_earned = models.TextField(blank=True)

    def __str__(self):
        return self.user.username

learn_to_code/client_app/forms.py
from django import forms
from django.contrib.auth.models import User
from client_app.models import Lesson

class ClientLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    

learn_to_code/client_app/views.py
from django.shortcuts import render
from client_app.forms import ClientLoginForm
from client_app.models import Lesson, ClientProfileInfo
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import Http404
import json

# Create your views here.
def index(request):
    return render(request, 'client_app/index.html')


def client_registration(request):
    registered = False
    if request.method == "POST":
        user_form = ClientLoginForm(data=request.POST)
        profile = ClientProfileInfo()
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile.user = user
            profile.current_lesson = 1
            profile.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = ClientLoginForm()
    return render(request, 'client_app/register.html', 
                context={ 'registered': registered, 'user_form': user_form })


def client_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('client_app:client_code'))
            else:
                return HttpResponseRedirect(reverse('client_registration'))
        else:
            print('Login failed.')
            print(f"Username: {username}  Password: {password}")
            return render(request, 'client_app/login.html', { 'error': 'Unsuccessful login attempt.' })
    else:
        return render(request, 'client_app/login.html')


@login_required
def client_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def code(request, lesson_number=1):
    current_lesson = int(request.user.clientprofileinfo.current_lesson)
    if lesson_number == 1:
        lesson_number = current_lesson
    try:
        lesson_info = Lesson.objects.get(pk=lesson_number)
    except LessonDoesNotExist:
        raise Http404("That lesson does not exist.")
    last_lesson = Lesson.objects.all().exclude(name="Not set").last()
    context = {'lesson': f"lessons/lesson_{lesson_number}.html", 'lesson_number': lesson_number, 'last_lesson': last_lesson.number }
    return render(request, 'client_app/code.html',  context=context)


@login_required
def lessons(request):
    completed_lessons = request.user.clientprofileinfo.completed_lessons.all()
    lessons = Lesson.objects.all().exclude(name="Not set")
    context = { 'lessons': lessons, 'completed_lessons': completed_lessons }
    print(f"User has completed these lessons: {completed_lessons}")
    return render(request, 'client_app/lessons.html', context=context)


@login_required
def reset(request):
    client_info = ClientProfileInfo.objects.get(user=request.user)
    client_info.completed_lessons.clear()
    client_info.save()
    lessons = Lesson.objects.all().exclude(name="Not set")
    context = { 'lessons': lessons, 'completed_lessons': '' }
    return render(request, 'client_app/lessons.html', context=context)


@login_required
def complete_lesson(request):
    if request.method == "POST":
        lesson_number = request.POST.get('lesson_number')
        client_info = ClientProfileInfo.objects.get(user=request.user)
        client_info.completed_lessons.add(Lesson.objects.get(number=lesson_number))
        client_info.save()
        print(f"Lesson {lesson_number} marked as complete.")
        return HttpResponse(json.dumps({'success': 'Lesson marked as complete.'}), content_type="application/json")

learn_to_code/templates/client_app/base.html
<!doctype html>
<html lang="en">
  <head>

    <!--   Built with love for my little brother Ayden   -->
    <!--   Jordan D. Murphy (2018)   Email: jdmurphy521@yahoo.com   Github: https://github.com/jd-murphy   -->
    <!--   Proudly built with Django. A huge thanks to all the wonderful folks who make Django so amazing!   -->
    <!--   Proudly built with Repl.it. A huge thanks to all the awesome people who work on Repl.it! You guys are so cool.  -->


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'client_app/minty.css' %}">
    <link rel="stylesheet" href="{% static 'client_app/mystyles.css' %}">
    <link rel="stylesheet" href="{% static 'client_app/custombox.min.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">

    <link rel="stylesheet" href="{% static 'client_app/light-modal.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/css/iziModal.min.css">

    

    {% block title_block %}
    {% endblock %}
  

  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}"><h3 class="brand_link">Learn 2 Code!</h3></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">HOME</a>
            </li>
        


            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'client_app:client_code' %}">CODE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'client_app:client_lessons' %}">LESSONS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'client_app:client_logout' %}">LOGOUT</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'client_app:client_registration' %}">SIGNUP</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'client_app:client_login' %}">LOGIN</a>
                </li>        
            {% endif %}


          </ul>
        </div>
      </nav>



      {% block body_block %}
      {% endblock %}












      <div class="light-modal" id="unique-id" role="dialog" aria-labelledby="light-modal-label" aria-hidden="false">
        <div class="light-modal-content animated ">
            <!-- light modal header -->
            <div class="light-modal-header">
                <a href="#" id="close-modal" class="light-modal-close-icon" aria-label="close">&times;</a>
            </div>
            <!-- light modal body -->
            <div class="light-modal-body">
                <!-- Your content -->
                <h1 class="congrats"> 🎉 Congrats! 🎉 </h1>
                <h3 class="congrats" id="congrats-msg">Great work, coder!</h3>
            </div>
            
            
        </div>
      </div>



    







      <footer class="footer mt-5">
        <div class="row">
          <div class="col">
            <p>This website was built by Jordan Murphy with Python and the Django framework.</p>
            <p>Jordan Murphy 2018</p>
          </div>
        </div>
      </footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'client_app/custombox.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/js/iziModal.min.js"></script> 
    <!-- http://izimodal.marcelodolce.com/ -->

    {% block custom_script %}
    {% endblock %}


    



    
  </body>
</html>

learn_to_code/templates/client_app/code.html
{% extends 'client_app/base.html' %}
{% load static %}
{% block title_block %}
<title>Learn 2 Code! | Code</title>
{% endblock %}

{% block body_block %}
    
        <div class="row main-content">
            <div class="col-6">
                
                {% include lesson %}

               
            </div>
            <div class="col">
                <iframe id="repl" height="600px" width="100%" src="https://repl.it/@jdmurphy/AcrobaticDeficientWebportal?lite=true" scrolling="no" frameborder="no" allowtransparency="true" allowfullscreen="true" sandbox="allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-modals"></iframe>
                <div class="row pt-4">
                    <div class="col-4 text-center">
                        
                            {% if lesson_number > 1 %}
                                <a class="btn btn-outline-info" href="{% url 'client_app:client_code' %}" id="previous_lesson_btn">< Back&nbsp;&nbsp;</a>
                            {% endif %}
                        
                    </div>
                    <div class="col-4 text-center">
                        
                            <a class="btn btn-outline-primary" href="#unique-id" id="success_button"> I got it to work!</a>
                        
                    </div>
                    <div class="col-4 text-center">
                        
                            {% if lesson_number != last_lesson %}
                                <a class="btn btn-outline-info animated " href="{% url 'client_app:client_code' %}" id="next_lesson_btn">&nbsp;&nbsp;Next ></a>
                            {% else %}
                            <a class="btn btn-outline-info" href="{% url 'client_app:client_lessons' %}">More lessons soon!</a>
                            {% endif %}
                        
                    </div>
                </div>
            </div>
        </div>


    
        
    
{% endblock %}

{% block custom_script %}
    <script src="{% static 'client_app/js-cookie.js' %}"></script>
    <script src="{% static 'client_app/myjs.js' %}"></script>
    <script src="{% static 'client_app/clipboard.min.js' %}"></script>
{% endblock %}

learn_to_code/templates/client_app/index.html
{% extends 'client_app/base.html' %}
{% load static %}
{% block title_block %}
<title>Learn 2 Code! | Home Page</title>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        <div class="jumbo_text">
            <div class="row">
                <div class="col-md-5">
                    <h1>Let's </b>Learn 2 Code!</h1>
                    <h3>Let's learn Python!</h3>
                </div>
                <div class="col-md-5">
                    <img src="{% static 'images/python_logo.png' %}" class="img-responsive mt-3" alt="Python Logo">
                </div>
            </div>
        </div>
    </div>
    
    <div class="container">
        <div class="row">
            <div class="col">
                <p>Wanna learn how to code? Well, you're in the right place. We are going to teach you how to master coding from step one, all the way to the top!</p>
                <p>We're going to start easy, and build a strong foundation so you can master the art of coding. We are going to learn Python. It's a really fun language to learn and it's super easy to get started.</p>
                <p>So what are you waiting for? Sign up, log in, and get coding! You can be writing your first lines of code in 60 seconds! Let's get started!</p>
                <br>
                <div class="row justify-content-center">
                    <a class="btn btn-success" href="{% url 'client_app:client_registration' %}">Let's CODE!</a>
                </div>
                <br>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5 mt-5">
                <blockquote>
                    This site was built for my little brother Ayden.
                    <br> 
                    You can do anything you want.
                    <br>
                    Be strong and work hard. 
                    <br>
                    There is no limit to what you can do!
                </blockquote>
            </div>
        </div>
    </div>

{% endblock %}

learn_to_code/templates/client_app/lessons.html
{% extends 'client_app/base.html' %}
{% load static %}
{% block title_block %}
<title>Learn 2 Code! | Lessons</title>
{% endblock %}

{% block body_block %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-6">
                <h1>Lessons</h1>
                <ul class="list-group mt-4">
                    {% for lesson in lessons %}
                        <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                            {% if lesson in completed_lessons %}
                                <img src="{% static 'images/completed.png' %}" alt="completed lesson" class="mr-3"><a href="{% url 'client_app:lesson_detail' lesson.number %}"><h5 class="pt-1">{{ lesson.number }}. {{ lesson.name }}</h5></a>
                            {% else %}
                                <img src="{% static 'images/incomplete.png' %}" alt="lesson not yet completed" class="mr-3"><a href="{% url 'client_app:lesson_detail' lesson.number %}"><h5 class="pt-1">{{ lesson.number }}. {{ lesson.name }}</h5></a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row mt-5 mb-5">
            <div class="col-3 justify-content-center">
                <a class="btn btn-info" href="{% url 'client_app:client_reset_progress' %}">Reset progress</a>
            </div>
        </div>
    </div>
{% endblock %}

learn_to_code/templates/client_app/login.html
{% extends 'client_app/base.html' %}
{% load static %}
{% block title_block %}
<title>Learn 2 Code! | Login</title>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        <div class="jumbo_text">
            <div class="row">
                <div class="col-md-5">
                    <h1>Login</h1>
                    <h3>Log in to start coding!</h3>
                </div>
                <div class="col-md-5">
                    <img src="{% static 'images/python_logo.png' %}" class="img-responsive mt-3" alt="Python Logo">
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        {% if error %}
            <div class="alert alert-dismissible alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Uh oh!</strong> That doesn't seem to be the correct login credentials. Try again!
            </div>
        {% endif %}
        <h1>Login</h1>
        <p>If you are not already signed up, <a href="{% url 'client_app:client_registration' %}">sign up here</a>!</p>
        <form action="{% url 'client_app:client_login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Enter Username...">
            <label for="password">Password:</label>
            <input type="password" name="password">
            <input type="submit" class="btn btn-success" value="Login">
        </form>
    </div>
{% endblock %}

learn_to_code/templates/client_app/register.html
{% extends 'client_app/base.html' %}
{% load static %}
{% block title_block %}
<title>Learn 2 Code! | Sign Up</title>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        <div class="jumbo_text">
            <div class="row">
                <div class="col-md-5">
                    <h1>Sign Up!</h1>
                    <h3>You can be writing code in 60 seconds!</h3>
                </div>
                <div class="col-md-5">
                    <img src="{% static 'images/python_logo.png' %}" class="img-responsive mt-3" alt="Python Logo">
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        {% if registered %}
            <div class="alert alert-dismissible alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Welcome!</strong> You're signed up. <a href="{% url 'client_app:client_login' %}" class="alert-link">Click here to log in to get started coding!</a>
              </div>
        {% else %}
            <h1>Sign up now!</h1>
            <h3>Just fill out this form:</h3>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                <input type="submit" class="btn btn-success" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}

learn_to_code/templates/lessons/lesson_10.html
<h1>Lesson 10</h1>
<h2>name = "Python Master"</h2>
<button class="btn btn-link" data-izimodal-open="#modal-iframe">Watch video lesson</button>

<p>Okay coder, we've seen how to put things in variables.
    But it isn't very useful to put something in a varibale and 
    then not do anything to it! Let's learn how to change a variable!
    You can change a variable the same way you set a variable. It's that simple. 
    We might set <b>name = "Python Beginner"</b> but soon we can change it to 
    <b>name = "Python Student"</b> and soon enough we'll have to change it to 
    <b>name = "Python Master"</b>! Make sure each assignment is on its own line. Try this out!
</p>
<div class="mt-3 mb-3 ml-5">
    <code>
        name = "Python Beginner"<br>
        print(name)<br>
        name = "Python Student"<br>
        print(name)<br>
        name = "Python Master"<br>
        print(name)
    </code>
</div>
<p>It is incredibly powerful to work with variables. We are going to be learning more ways to 
    work with variables soon. It's going to get <em>really</em> fun!
</p>


<div id="modal-iframe" aria-hidden="true" aria-labelledby="modal-iframe" role="dialog" class="iziModal" data-izimodal-group="grupo1" style="background: black; z-index: 999; border-radius: 3px; overflow: hidden; max-width: 600px; display: none; height: 445px;">
    <div class="iziModal-header iziModal-noSubtitle" style="background: rgb(0, 0, 0); padding-right: 70px;">
      <i class="iziModal-header-icon icon-settings_system_daydream"></i>
      <h2 class="iziModal-header-title">Video | Lesson 10</h2>
      <p class="iziModal-header-subtitle"></p>
      <div class="iziModal-header-buttons">
        <a href="javascript:void(0)" class="iziModal-button iziModal-button-close" data-izimodal-close=""></a>
        <!-- <a href="javascript:void(0)" class="iziModal-button iziModal-button-fullscreen" data-izimodal-fullscreen=""></a> -->
      </div>
    </div>
    <div class="iziModal-wrap" style="height: auto;">
      <div class="iziModal-content" style="padding: 0px;">
        <iframe class="iziModal-iframe" style="height: 400px;" src="https://player.vimeo.com/video/300898934" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>
    </div>
  </div>
  

<input type="hidden" id="lesson_number" value="10">

learn_to_code/templates/lessons/lesson_113.html
<h1>Lesson 113</h1>
<h2>Variables are awesome!</h2>

<p>Okay coder, we've seen how
     to do some math, but most of the time 
    we won't be doing math inside a <b>print()</b> statement. 
    How can we do math outside a <b>print()</b> statement 
    and still see the result? Well my friend, the magic is in <b>variables</b>!
    Python uses variables to store information. Try this 
</p>
<div class="mt-3 mb-3 ml-5">
    <code>
        result = 5 * 16<br>
        print(result)
    </code>
</div>
<p>Don't use quotes <b>" "</b>, just print out the variable 
    named <b>result</b>. Look in the console and you'll see the magic!</p> 
<div class="mt-3 mb-3 ml-5">
    <code>80</code>
</div>
<p>Variables are amazing and we'll learn a lot more about them soon. For now, try storing 
    <b>19 plus 17</b> and then <b>5 minus 17</b> in <b>result</b>. Make sure to <b>print(result)</b> to see your answers!</p>

<input type="hidden" id="lesson_number" value="113">

learn_to_code/templates/lessons/lesson_115.html
<h1>Lesson 115</h1>
<h2>Variables are awesome!</h2>

<p>Okay coder, we've seen how
     to do some math, but most of the time 
    we won't be doing math inside a <b>print()</b> statement. 
    How can we do math outside a <b>print()</b> statement 
    and still see the result? Well my friend, the magic is in <b>variables</b>!
    Python uses variables to store information. Try this 
</p>
<div class="mt-3 mb-3 ml-5">
    <code>
        result = 5 * 16<br>
        print(result)
    </code>
</div>
<p>Don't use quotes <b>" "</b>, just print out the variable 
    named <b>result</b>. Look in the console and you'll see the magic!</p> 
<div class="mt-3 mb-3 ml-5">
    <code>80</code>
</div>
<p>Variables are amazing and we'll learn a lot more about them soon. For now, try storing 
    <b>19 plus 17</b> and then <b>5 minus 17</b> in <b>result</b>. Make sure to <b>print(result)</b> to see your answers!</p>

<input type="hidden" id="lesson_number" value="115">

learn_to_code/templates/lessons/lesson_143.html
<h1>Lesson 143</h1>
<h2>Variables are awesome!</h2>

<p>Okay coder, we've seen how
     to do some math, but most of the time 
    we won't be doing math inside a <b>print()</b> statement. 
    How can we do math outside a <b>print()</b> statement 
    and still see the result? Well my friend, the magic is in <b>variables</b>!
    Python uses variables to store information. Try this 
</p>
<div class="mt-3 mb-3 ml-5">
    <code>
        result = 5 * 16<br>
        print(result)
    </code>
</div>
<p>Don't use quotes <b>" "</b>, just print out the variable 
    named <b>result</b>. Look in the console and you'll see the magic!</p> 
<div class="mt-3 mb-3 ml-5">
    <code>80</code>
</div>
<p>Variables are amazing and we'll learn a lot more about them soon. For now, try storing 
    <b>19 plus 17</b> and then <b>5 minus 17</b> in <b>result</b>. Make sure to <b>print(result)</b> to see your answers!</p>

<input type="hidden" id="lesson_number" value="143">

learn_to_code/templates/lessons/lesson_227.html
<h1>Lesson 227</h1>
<h2>Variables are awesome!</h2>

<p>Okay coder, we've seen how
     to do some math, but most of the time 
    we won't be doing math inside a <b>print()</b> statement. 
    How can we do math outside a <b>print()</b> statement 
    and still see the result? Well my friend, the magic is in <b>variables</b>!
    Python uses variables to store information. Try this 
</p>
<div class="mt-3 mb-3 ml-5">
    <code>
        result = 5 * 16<br>
        print(result)
    </code>
</div>
<p>Don't use quotes <b>" "</b>, just print out the variable 
    named <b>result</b>. Look in the console and you'll see the magic!</p> 
<div class="mt-3 mb-3 ml-5">
    <code>80</code>
</div>
<p>Variables are amazing and we'll learn a lot more about them soon. For now, try storing 
    <b>19 plus 17</b> and then <b>5 minus 17</b> in <b>result</b>. Make sure to <b>print(result)</b> to see your answers!</p>

<input type="hidden" id="lesson_number" value="227">

learn_to_code/templates/lessons/lesson_235.html
<h1>Lesson 235</h1>
<h2>Variables are awesome!</h2>

<p>Okay coder, we've seen how
     to do some math, but most of the time 
    we won't be doing math inside a <b>print()</b> statement. 
    How can we do math outside a <b>print()</b> statement 
    and still see the result? Well my friend, the magic is in <b>variables</b>!
    Python uses variables to store information. Try this 
</p>
<div class="mt-3 mb-3 ml-5">
    <code>
        result = 5 * 16<br>
        print(result)
    </code>
</div>
<p>Don't use quotes <b>" "</b>, just print out the variable 
    named <b>result</b>. Look in the console and you'll see the magic!</p> 
<div class="mt-3 mb-3 ml-5">
    <code>80</code>
</div>
<p>Variables are amazing and we'll learn a lot more about them soon. For now, try storing 
    <b>19 plus 17</b> and then <b>5 minus 17</b> in <b>result</b>. Make sure to <b>print(result)</b> to see your answers!</p>

<input type="hidden" id="lesson_number" value="235">

learn_to_code/templates/lessons/lesson_322.html
<h1>Lesson 322</h1>
<h2>Variables are awesome!</h2>

<p>Okay coder, we've seen how
     to do some math, but most of the time 
    we won't be doing math inside a <b>print()</b> statement. 
    How can we do math outside a <b>print()</b> statement 
    and still see the result? Well my friend, the magic is in <b>variables</b>!
    Python uses variables to store information. Try this 
</p>
<div class="mt-3 mb-3 ml-5">
    <code>
        result = 5 * 16<br>
        print(result)
    </code>
</div>
<p>Don't use quotes <b>" "</b>, just print out the variable 
    named <b>result</b>. Look in the console and you'll see the magic!</p> 
<div class="mt-3 mb-3 ml-5">
    <code>80</code>
</div>
<p>Variables are amazing and we'll learn a lot more about them soon. For now, try storing 
    <b>19 plus 17</b> and then <b>5 minus 17</b> in <b>result</b>. Make sure to <b>print(result)</b> to see your answers!</p>

<input type="hidden" id="lesson_number" value="322">